version: '3.8'

services:
  autogen-app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - DEMO_REQUEST=ショッピングを楽しみたいです
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true